workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    # NO automatic triggers - manual only
    triggering:
      events: []
      branch_patterns: []

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.x5marketing.mobile
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --build-name=1.0.3 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
